id: D73500F4B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-18T10:49:14+00:00'
last_modified: '2022-05-30T03:59:46.180710+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    28df:
      image_group_id: I1PD95937
      title: འདུལ་བའི་མདོའི་འགྲེལ་པ།
      total_pages: 1125
      order: 92
      base_file: 28df.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
