id: P191F2189
initial_creation_type: ocr
source_metadata:
  volumes:
    ca3ed7acba424240aab552b310b7f022:
      base_file: v092.txt
      image_group_id: I1PD95937
      title: འདུལ་བའི་མདོའི་འགྲེལ་པ།
      total_pages: 1125
      volume_number: 92
vol2fn:
  v092: v092.txt
